### ISSUE TITLE
Add region and year to config

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [Urban-Analytics-Technology-Platform/acbm#64]
- years: remove from [here](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/ada37b208329c1a550a78c8a900065a77db36715/scripts/2_match_households_and_individuals.py#L248) and specify in config
- regions: remove from [here](https://github.com/Urban-Analytics-Technology-Platform/acbm/blob/ada37b208329c1a550a78c8a900065a77db36715/scripts/2_match_households_and_individuals.py#L259) and specify in config. See also https://github.com/Urban-Analytics-Technology-Platform/acbm/issues/16#issuecomment-2451809737

**Comment by sgreenbury** [comment]
Adding the table with proportion of trips by public transport with groupby region that we explored for motivating this feature:
```
| IndWkGOR_B02ID           |   proportion |
|:-------------------------|-------------:|
| DNA                      |        0.098 |
| East Midlands            |        0.059 |
| East of England          |        0.065 |
| London                   |        0.246 |
| NA                       |        0.138 |
| North East               |        0.105 |
| North West               |        0.082 |
| Scotland                 |        0.11  |
| South East               |        0.071 |
| South West               |        0.049 |
| Wales                    |        0.062 |
| West Midlands            |        0.073 |
| Yorkshire and the Humber |        0.08  |
```
