### ISSUE TITLE
Task 1: Add activity patterns to synthetic population

### ISSUE THREAD

**Issue by HSalat** [Urban-Analytics-Technology-Platform/acbm#8]
- [ ] Task 1a: Explore current data 
  - [ ] TUS (public) (MVP)
  - [ ] NTS (private, available but needs understanding for Tech Plat use) (for future)
- [ ] Task 1b: Add activity chains to population (scoping)
  - [ ] Step 1: Statisical matching (Propensity score matching) OR categorical matching (MVP) - AS DONE IN SPC
  - [ ] Step 2: Convert matched dataset to activity chain 
  - [ ] Future improvements
  - [ ] Markov chain model (for future)
  - [ ] Bayesian network model (for future)
 - [ ] Task 1c: Validate activity sequences 
   - [ ] sequence alignment methods (for future)

--
Comments (HS):
- 1a: TUS appears ill-fitted compared to NTS for the task; -> NTS-SPC merge
- 1b/1: I'm skeptical of PSM from previous merge attempts. Identify (1) matching variables and (2) method
- NTS sample (non special access): Trips contain low numbers of NAs and for non-important variables only (~1.2% of start times missing). It seems only almost complete cases were kept in the sample -> how do we know how exhaustive the data is for one particular individual?

**Comment by Hussein-Mahfouz** [comment]
> 1b/1: I'm skeptical of PSM from previous merge attempts. Identify (1) matching variables and (2) method

In terms of methods, I need to:
- Understand PSM 
- Compare PSM to the statistical matching approach mentioned in [Synthetic population and travel demand for Paris and Île-de-France based on open and publicly available data](https://www.sciencedirect.com/science/article/pii/S0968090X21003016) and choose one

Optional / Future Enhancements:
- Bayesian Networks: [paper](https://www.sciencedirect.com/science/article/pii/S1877050923005707), [code](https://github.com/AuroreSallard/BayesianNetworks_v2/blob/main/Networks/BNutils.py)
